clc;
clear all;

n = -5:1:15;
u1 = (n>=1);
u5 = (n>=5);
x = u1-u5;
h = (1-abs((n-6)/4)).*(abs((n-6)/4)<1);

conv(x,h);
n1 = -11:1:29;

subplot(3,1,1);
stem(n,x,'filled', 'r', 'MarkerSize', 3, 'linewidth', 1);
xlabel('n------>');
ylabel('x[n]');
set(gca, ...
    'Box', 'off', ...
    'TickDir', 'out', ...
    'YGrid', 'on', ...
    'Xtick', [-6:2:16], ...
    'FontSize', 20, ...
    'FontName', 'Calibri');
axis([-5 15 0 2.1]);

subplot(3,1,2);
stem(n,h,'filled', 'b', 'MarkerSize', 3, 'linewidth', 1);
xlabel('n------>');
ylabel('h[n]');
set(gca, ...
    'Box', 'off', ...
    'TickDir', 'out', ...
    'YGrid', 'on', ...
    'Xtick', [-6:2:16], ...
    'FontSize', 20, ...
    'FontName', 'Calibri');
axis([-5 15 0 2.1]);

subplot(3,1,3);
stem(n1,conv(x,h),'filled', 'm', 'MarkerSize', 3, 'linewidth', 1);
xlabel('n------>');
ylabel('conv[n]');
set(gca, ...
    'Box', 'off', ...
    'TickDir', 'out', ...
    'YGrid', 'on', ...
    'Xtick', [-6:2:16], ...
    'FontSize', 20, ...
    'FontName', 'Calibri');
axis([-5 15 0 3.1]);


