clc;
clear all;

n=-10:1:20;
u = (n>=0);
s = 2*[(-1/2).^(n)-1].*u;

subplot(3,1,1);
stem(n,s,'filled', 'r', 'MarkerSize', 3, 'linewidth', 1);
xlabel('n------>');
ylabel('s[n]');
set(gca, ...
    'Box', 'off', ...
    'TickDir', 'out', ...
    'YGrid', 'on', ...
    'Xtick', [-6:2:16], ...
    'FontSize', 20, ...
    'FontName', 'Calibri');
axis([-2 10 -3.1 0]);

for i=2:31
  s2(i) = s(i)-s(i-1);
endfor
subplot(3,1,2);
stem(n,s2,'filled', 'b', 'MarkerSize', 3, 'linewidth', 1);
xlabel('n------>');
ylabel('h[n]');
set(gca, ...
    'Box', 'off', ...
    'TickDir', 'out', ...
    'YGrid', 'on', ...
    'Xtick', [-6:2:16], ...
    'FontSize', 20, ...
    'FontName', 'Calibri');
axis([-2 10 -3.1 2]);

n1 = -19:1:41;
subplot(3,1,3);
x = n.*u;
y = conv(x,s2);
stem(n1,y,'filled', 'm', 'MarkerSize', 3, 'linewidth', 1);
xlabel('n------>');
ylabel('conv[n] for x[n] = nu[n] ');
set(gca, ...
    'Box', 'off', ...
    'TickDir', 'out', ...
    'YGrid', 'on', ...
    'Xtick', [-6:2:16], ...
    'FontSize', 20, ...
    'FontName', 'Calibri');
axis([-2 10 -20 0]);
hold on;

windowsize = 2;
b = (1/windowsize)*ones(1,windowsize);
yfiltered = filter(b, 1, y);
plot(n1, yfiltered, 'r', 'linewidth', 0.5);